WEBBANDIENTHOAI/Models/MFC/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEBBANDIENTHOAI.Models.MFC
{
    [Table("tb_Contact")]
    public class Contact : CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(150, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Name { get; set; }
        [StringLength(150, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Email { get; set; }
        public string Website { get; set; }
        [StringLength(4000)]
        public string Message { get; set; }
        public bool IsRead { get; set; }
    }
}

WEBBANDIENTHOAI/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBBANDIENTHOAI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Quanliphu")]
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }



    }
}

WEBBANDIENTHOAI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;
using WEBBANDIENTHOAI.Models.MFC;

namespace WEBBANDIENTHOAI.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DangKy_Partial()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult DangKy(Subscribe req)
        {
            // check hộp lệ
            if (ModelState.IsValid)
            {
                data.Subscribes.Add(new Subscribe { Email = req.Email, CreatedDate = DateTime.Now });
                data.SaveChanges();
                return Json(new { Success = true });
            }
            return View("Partial_Subcrice", req);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Refresh()
        {
            var item = new ThongKeModel();

            ViewBag.Visitors_online = HttpContext.Application["visitors_online"];
            var hn = HttpContext.Application["HomNay"];
            item.HomNay = HttpContext.Application["HomNay"].ToString();
            item.HomQua = HttpContext.Application["HomQua"].ToString();
            item.TuanNay = HttpContext.Application["TuanNay"].ToString();
            item.TuanTruoc = HttpContext.Application["TuanTruoc"].ToString();
            item.ThangNay = HttpContext.Application["ThangNay"].ToString();
            item.ThangTruoc = HttpContext.Application["ThangTruoc"].ToString();
            item.TatCa = HttpContext.Application["TatCa"].ToString();
            return PartialView(item);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

WEBBANDIENTHOAI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;

namespace WEBBANDIENTHOAI.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        //ngoài trang index home
        public ActionResult MenuTop()
        {
            var items = data.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("_MenuTop", items);
        }
        //ngoài trang index home
        public ActionResult MenuProductCategory()
        {
            var items = data.ProductCategories.ToList();
            return PartialView("_MenuProductCategory", items);
        }

        //ngoài trang index home
        public ActionResult MenuProductRight(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = data.ProductCategories.ToList();
            return PartialView("_MenuProductRight", items);
        }


        // trong trang Product
        public ActionResult MnTraiProduct(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = data.ProductCategories.ToList();
            return PartialView("_MnTraiProduct", items);
        }
    }
}

WEBBANDIENTHOAI/Controllers/ProductsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;
using WEBBANDIENTHOAI.Models.MFC;

namespace WEBBANDIENTHOAI.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Products

        // phần Product sản phẩm trang show all sản phẩm
        public ActionResult Index(int? page, string Searchtext, string sortOrder)
        {
            ViewBag.SortByName = String.IsNullOrEmpty(sortOrder) ?"ten_desc" : "";
            ViewBag.SortByPrice = (sortOrder == "dongia" ? "dongia_desc" : "dongia"); 
          
            IEnumerable<Product> items = data.Products.OrderByDescending(x => x.Id);
           
            switch(sortOrder)
            {
                case "ten_desc":
                    items = data.Products.OrderByDescending(x => x.Title);
                    break;
                case "dongia_desc":
                    items = data.Products.OrderByDescending(x => x.Price);
                    break;
                case "dongia":
                    items = data.Products.OrderBy(x => x.Price);
                    break;
                default: // mặc định sắp xếp theo tên sản phẩm
                    items = data.Products.OrderBy(x => x.Title);
                    break;

            }
          
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }

            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
           
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
            //var items = data.Products.ToList();

            //return View(items);

        }

        // chi tiết sản phẩm sản phẩm 
        public ActionResult Detail(string alias, int id)
        {
            var item = data.Products.Find(id);
            // đếm số lượt truy cập vô sản phẩm đó
            if (item != null)
            {
                data.Products.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                data.Entry(item).Property(x => x.ViewCount).IsModified = true;
                data.SaveChanges();
            }

            return View(item);
        }

        // Trang sản phẩm nhưng theo danh mục ấn vào danh mục điện thoại thì sẻ sử lí show trang điện thoại
        public ActionResult ProductCategory(string alias, int id, string Searchtext, string sortOrder, int? page)
        {

            ViewBag.SortByName = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.SortByPrice = (sortOrder == "dongia" ? "dongia_desc" : "dongia");

            IEnumerable<Product> items = data.Products.OrderByDescending(x => x.Id);

            switch (sortOrder)
            {
                case "ten_desc":
                    items = data.Products.OrderByDescending(x => x.Title);
                    break;
                case "dongia_desc":
                    items = data.Products.OrderByDescending(x => x.Price);
                    break;
                case "dongia":
                    items = data.Products.OrderBy(x => x.Price);
                    break;
                default: // mặc định sắp xếp theo tên sản phẩm
                    items = data.Products.OrderBy(x => x.Title);
                    break;

            }

            //var items = data.Products.ToList();
            if (id > 0)
            {
                items = items.Where(x => x.ProductCategoryId == id).ToList();
            }
            var cate = data.ProductCategories.Find(id);
            if (cate != null)
            {
                ViewBag.CateName = cate.Title;
            }
            var CateId = 5;
            if (page == null)
            {
                page = 1;
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, CateId);
            ViewBag.CateId = id;
            ViewBag.Page = page;
            return View(items);
        }


        // sử lí từng phần sản phẩm theo tên sản phẩm ngoài trang chủ, Điện Thoai, Máy Tính, Đồng Hồ
        public ActionResult Partial_ItemsByCateId()
        {
            var items = data.Products.Where(x => x.IsHome && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

        //
        public ActionResult ProductSales()
        {
            var items = data.Products.Where(x => x.IsSale && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

       
    }
}

WEBBANDIENTHOAI/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;

namespace WEBBANDIENTHOAI.Controllers
{
    public class TinTucController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: TinTuc
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TinTuc_Partial()
        {
            var items = data.News.Take(4).ToList();
            return PartialView(items);
        }
    }
}

WEBBANDIENTHOAI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WEBBANDIENTHOAI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WEBBANDIENTHOAI/Views/Home/DangKy_Partial.cshtml
@model WEBBANDIENTHOAI.Models.MFC.Subscribe

<section class="section-subscribe padding-y-lg">
    <div class="container">

        <p class="pb-2 text-center text-white">Cung cấp các xu hướng sản phẩm mới nhất và tin tức ngành trực tiếp đến các bạn</p>

        <div class="row justify-content-md-center">
            @using (Ajax.BeginForm("DangKy", "Home", new AjaxOptions
            {
                OnBegin = "OnBeginSub",
                OnSuccess = "OnSuccessSub",
                OnFailure = "OnFailureSub"
            }))
            {
                @Html.AntiForgeryToken()
                <script>
                    function OnBeginSub() {

                    }
                    function OnSuccessSub(rs) {
                        if (rs.Success) {
                            alert("Thành Công");
                        }
                    }
                    function OnFailureSub(rs) { alert("Lỗi gửi"); }
                </script>
                <div style="margin-left: 170px;" class="col-lg-5 col-md-6">
                    <form class="form-row">
                        <div class="col-md-8 col-7">

                            <input style="width: 290px;" name="Email" class="form-control border-0" placeholder="Email bạn" type="email">
                        </div> <!-- col.// -->
                        <div style="margin-left: 55px;" class="col-md-4 col-5">
                            <button style="width: 190px;" type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Đăng ký </button>
                        </div> <!-- col.// -->
                    </form>
                    <small class="form-text text-white-50">Chúng tôi sẽ không bao giờ chia sẻ thông tin của bạn với những nguồn thông tin lạ. </small>
                </div> <!-- col-md-6.// -->
            }

        </div>


    </div>
</section>

WEBBANDIENTHOAI/Views/Home/Index.cshtml
@model IEnumerable<WEBBANDIENTHOAI.Models.MFC.Product>

@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <!-- ========================= SECTION MAIN  ========================= -->
    <section class="section-main padding-y">
        <main class="card">
            <div class="card-body">

                <div class="row">

                    @Html.Action("MenuProductCategory", "Menu")

                    <div class="col-md-9 col-xl-7 col-lg-7">

                        <!-- ================== COMPONENT SLIDER  BOOTSTRAP  ==================  -->
                        <div id="carousel1_indicator" class="slider-home-banner carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="1"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">

                                    <img src="~/Content/images/banners/sl2.jpg" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banners/sl1.jpg" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banners/sl3.jpg" alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carousel1_indicator" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel1_indicator" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!-- ==================  COMPONENT SLIDER BOOTSTRAP end.// ==================  .// -->

                    </div> <!-- col.// -->
                    <div class="col-md d-none d-lg-block flex-grow-1">
                        @*<aside class="special-home-right">
                                <h6 class="bg-blue text-center text-white mb-0 p-2">Danh mục phổ biến</h6>
                                @foreach (var item in Model.ListCategory.Where(n => n.ShowOnHomePage == true).Take(3))
                                {
                                    <div class="card-banner border-bottom">
                                        <div class="py-3" style="width:80%">
                                            <div>
                                                @Html.ActionLink(item.Name, "ProductCategory", "Category", new { @Id = item.Id }, null)
                                            </div>


                                            <a href="@Url.Action("ProductCategory", "Category", new { Id = item.Id })" class="btn btn-secondary btn-sm"> Xem ngay </a>


                                        </div>
                                        <a href="@Url.Action("ProductCategory", "Category", new { Id = item.Id })">
                                            <img src="~/Content/images/items/@item.Avartar" height="80" class="img-bg">
                                        </a>

                                    </div>
                                }


                            </aside>*@
                        @Html.Action("MenuProductRight", "Menu", new { id = ViewBag.CateId })
                    </div> <!-- col.// -->
                </div> <!-- row.// -->

            </div> <!-- card-body.// -->
        </main> <!-- card.// -->

    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->
    <!-- =============== SECTION DEAL =============== -->
    <section class="padding-bottom">
        <div class="card card-deal">
            <div class="col-heading content-body">
                <header class="section-heading">
                    <h3 class="section-title">Giảm giá sốc</h3>
                    <p>Thời gian giảm giá</p>
                </header><!-- sect-heading -->
                <div class="timer">
                    <div> <span class="num">04</span> <small>Ngày</small></div>
                    <div> <span class="num">12</span> <small>Giờ</small></div>
                    <div> <span class="num">58</span> <small>Phút</small></div>
                    <div> <span class="num">02</span> <small>Giây</small></div>
                </div>
            </div> <!-- col.// -->
            @Html.Action("ProductSales", "Products")
            <!--<div class="row no-gutters items-wrap">-->
            @*@foreach (var item in Model.ListProduct.Where(n => n.TypeId == 1).Take(3))*@
            <!--{
            <div class="col-md col-6">
                <figure class="card-product-grid card-sm">-->
            @*<a href="@Url.Action("Detail", "Product", new { Id = item.Id })" class="img-wrap">*@
            @*<img src="~/Content/images/@item.Avartar">*@



            <!--<div class="text-wrap p-3">-->
            @*@<a href="#" class="title">@item.Name</a>*@
            @*@Html.ActionLink(item.Name, "Detail", "Product", new { Id = item.Id }, null)*@
            <!--<span class="badge badge-danger"> -20% </span>
                    </div>
                </figure>
            </div>-->
            <!-- col.// -->
            <!--}

            </div>-->
        </div>

    </section>
    <!-- =============== SECTION DEAL // END =============== -->
    <!-- =============== SECTION 1 =============== -->
    <!--<section class="padding-bottom">
        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Apple</h4>
        </header>

        <div class="card card-home-category">
            <div class="row no-gutters">
                <div class="col-md-3">

                    <div class="home-category-banner bg-light-orange">
                        <h5 class="title">Sản phẩm apple thịnh hành hiện nay</h5>
                        <p>Các dòng sản phẩm nổi bật sẻ luôn được chúng tôi cập nhập thường xuyên. </p>
                        <a href="#" class="btn btn-outline-primary rounded-pill">Xem ngay</a>
                        <img src="~/Content/images/items/anhdaidieniphone1.jpg" class="img-bg">
                    </div>

                </div> <!-- col.// -->
    <!--<div class="col-md-9">
        <ul class="row no-gutters bordered-cols">-->
    @*@foreach (var item in Model.ListProduct.Where(n => n.BrandId == 1).Take(8))
        {
            <li class="col-6 col-lg-3 col-md-4">
                <a href="@Url.Action("Detail", "Product", new { Id = item.Id })" class="item">
                    <div class="card-body">

                        <h6 class="title"> @item.Name </h6>
                        <img class="img-sm float-right" src="~/Content/images/@item.Avartar">

                        <h6 class="text-muted"><i class="fa fa-map-marker-alt"></i> @String.Format("{0:0,0}", @item.Price) VNĐ</h6>
                        <a class="btn btn-success" href="@Url.Action("Detail", "Product", new { Id = item.Id })">Chi Tiết</a>



                    </div>
                </a>
            </li>

        }*@


    <!--</ul>
    </div>-->
    <!-- col.// -->
    @Html.Action("Partial_ItemsByCateId", "Products")
    <!--</div>--> <!-- row.// -->
    <!--</div>--> <!-- card.// -->
    <!--</section>-->
    <!-- =============== SECTION 1 END =============== -->
    <!-- =============== SECTION 2 =============== -->
    <!--<section class="padding-bottom">
        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Samsung</h4>
        </header>

        <div class="card card-home-category">
            <div class="row no-gutters">
                <div class="col-md-3">

                    <div class="home-category-banner bg-light-orange">
                        <h5 class="title">Sản phẩm Samsung phổ biến hiện nay</h5>
                        <p>Các dòng sản phẩm nổi bật sẻ luôn được chúng tôi cập nhập thường xuyên. </p>
                        <a href="#" class="btn btn-outline-primary rounded-pill">Xem ngay</a>
                        <img src="~/Content/images/items/samsungdaidien3.jpg" class="img-bg">
                    </div>

                </div> <!-- col.// -->
    <!--<div class="col-md-9">
        <ul class="row no-gutters bordered-cols">-->
    @*@foreach (var item in Model.ListProduct.Where(n => n.BrandId == 2).Take(8))*@
    <!--{
    <li class="col-6 col-lg-3 col-md-4">-->
    @*<a href="@Url.Action("Detail", "Product", new { Id = item.Id })" class="item">*@
    <!--<div class="card-body">-->
    @*<h6 class="title"> @item.Name </h6>
        <img class="img-sm float-right" src="~/Content/images/@item.Avartar">*@

    @*<h6 class="text-muted"><i class="fa fa-map-marker-alt"></i> @String.Format("{0:0,0}", @item.Price) VNĐ</h6>*@


    <!--</div>
                </a>
            </li>

            }
        </ul>
    </div>-->
    <!-- col.// -->
    <!--</div>--> <!-- row.// -->
    <!--</div>--> <!-- card.// -->
    <!--</section>-->
    <!-- =============== SECTION 2 END =============== -->
    <!-- =============== SECTION ITEMS =============== -->
    <!--<section class="padding-bottom-sm">

        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Sản Phẩm Đề Xuất</h4>
        </header>

        <div class="row row-sm">-->
    @*@foreach (var item in Model.ListProduct.Where(n => n.TypeId == 2).Take(12))*@
    <!--{
    <div class="col-xl-2 col-lg-3 col-md-4 col-6">
        <div href="#" class="card card-sm card-product-grid">-->
    @*<a href="@Url.Action("Detail", "Product", new { Id = item.Id })" class="img-wrap"> <img src="~/Content/images/@item.Avartar"> </a>*@
    <!--<figcaption class="info-wrap">-->
    @*<a href="#" class="title">@item.Name</a>*@
    @*@Html.ActionLink(item.Name, "Detail", "Product", new { Id = item.Id }, null)*@
    @*<div class="price mt-1">@String.Format("{0:0,0}", @item.Price) VNĐ</div>  price-wrap.//*@
    <!--</figcaption>
        </div>
    </div>-->
    <!-- col.// -->
    <!--}



    </div>-->
    <!-- row.// -->
    <!--</section>-->
    <!-- =============== SECTION ITEMS .//END =============== -->
    <!-- =============== SECTION SERVICES =============== -->
    @Html.Action("TinTuc_Partial", "TinTuc")
    <!-- =============== SECTION SERVICES .//END =============== -->
    <!-- =============== SECTION REGION .//END =============== -->

    <article class="my-4">
        <img src="~/Content/images/banners/ad-sm.png" class="w-100">
    </article>
</div>
<!-- container end.// -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
@Html.Action("DangKy_Partial", "Home")
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->
<!-- ========================= FOOTER ========================= -->

WEBBANDIENTHOAI/Views/Home/Refresh.cshtml
@model WEBBANDIENTHOAI.Models.ThongKeModel
@if (Model != null)
{
    <div class="thongke">
        <table class="table">
            <tr>
                <td>Hôm nay</td>
                <td>@Model.HomNay</td>
            </tr>
            <tr>
                <td>Hôm qua</td>
                <td>@Model.HomQua</td>
            </tr>
            <tr>
                <td>Tuần này</td>
                <td>@Model.TuanNay</td>
            </tr>
            <tr>
                <td>Số người Online</td>
                <td>@ViewBag.Visitors_online</td>
            </tr>
        </table>
    </div>

}