WEBBANDIENTHOAI/Models/MFC/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBBANDIENTHOAI.Models.MFC
{

    [Table("tb_Product")]
    public class Product : CommonAbstract
    {
        public Product()
        {
            this.ProductImage = new HashSet<ProductImage>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Title { get; set; }

        [StringLength(250)]
        public string Alias { get; set; }

        [StringLength(50)]
        public string ProductCode { get; set; }
        public string Description { get; set; }

        [AllowHtml]
        public string Detail { get; set; }

        [StringLength(250)]
        public string Image { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal Price { get; set; }
        public decimal? PriceSale { get; set; }
        public int Quantity { get; set; }
        public int ViewCount { get; set; }
        public bool IsHome { get; set; }
        public bool IsSale { get; set; }
        public bool IsFeature { get; set; }
        public bool IsHot { get; set; }
        public bool IsActive { get; set; }
        public int ProductCategoryId { get; set; }

        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(250)]
        public string SeoKeywords { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

WEBBANDIENTHOAI/Models/MFC/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEBBANDIENTHOAI.Models.MFC
{
    [Table("tb_ProductCategory")]
    public class ProductCategory : CommonAbstract
    {
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }
        public string Description { get; set; }
        [StringLength(250)]
        public string Icon { get; set; }
        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(250)]
        public string SeoKeywords { get; set; }

        public ICollection<Product> Products { get; set; }
    }
}

WEBBANDIENTHOAI/Areas/Admin/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;
using WEBBANDIENTHOAI.Models.MFC;

namespace WEBBANDIENTHOAI.Areas.Admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Admin/ProductCategory
        public ActionResult Index()
        {
            var items = data.ProductCategories;
            return View(items);
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.Alias = WEBBANDIENTHOAI.Models.Common.Filter.FilterChar(model.Title);
                data.ProductCategories.Add(model);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            var item = data.ProductCategories.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedDate = DateTime.Now;
                model.Alias = WEBBANDIENTHOAI.Models.Common.Filter.FilterChar(model.Title);
                data.ProductCategories.Attach(model);
                data.Entry(model).State = System.Data.Entity.EntityState.Modified;
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

WEBBANDIENTHOAI/Areas/Admin/Controllers/ProductsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;
using WEBBANDIENTHOAI.Models.MFC;

namespace WEBBANDIENTHOAI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Quanliphu")]
    public class ProductsController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Admin/Products
        public ActionResult Index(int? page, string Searchtext)
        {
            IEnumerable<Product> items = data.Products.OrderByDescending(x => x.Id);
            var pageSize = 8;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Add()
        {
            ViewBag.ProductCategory = new SelectList(data.ProductCategories.ToList(), "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Product model, List<string> Images, List<int> rDefault)
        {
            if (ModelState.IsValid)
            {
                if (Images != null && Images.Count > 0)
                {
                    for (int i = 0; i < Images.Count; i++)
                    {
                        if (i + 1 == rDefault[0])
                        {
                            model.Image = Images[i];
                            model.ProductImage.Add(new ProductImage
                            {
                                ProductId = model.Id,
                                Image = Images[i],
                                IsDefault = true
                            });
                        }
                        else
                        {
                            model.ProductImage.Add(new ProductImage
                            {
                                ProductId = model.Id,
                                Image = Images[i],
                                IsDefault = false
                            });
                        }
                    }
                }
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                if (string.IsNullOrEmpty(model.SeoTitle))
                {
                    model.SeoTitle = model.Title;
                }
                if (string.IsNullOrEmpty(model.Alias))
                    model.Alias = WEBBANDIENTHOAI.Models.Common.Filter.FilterChar(model.Title);
                data.Products.Add(model);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductCategory = new SelectList(data.ProductCategories.ToList(), "Id", "Title");
            return View(model);
        }


        public ActionResult Edit(int id)
        {
            ViewBag.ProductCategory = new SelectList(data.ProductCategories.ToList(), "Id", "Title");
            var item = data.Products.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedDate = DateTime.Now;
                model.Alias = WEBBANDIENTHOAI.Models.Common.Filter.FilterChar(model.Title);
                data.Products.Attach(model);
                data.Entry(model).State = System.Data.Entity.EntityState.Modified;
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = data.Products.Find(id);
            if (item != null)
            {
                data.Products.Remove(item);
                data.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }

        // Sự lí hiện thị tổng
        [HttpPost]
        public ActionResult IsActive(int id)
        {
            var item = data.Products.Find(id);
            if (item != null)
            {
                item.IsActive = !item.IsActive;
                data.Entry(item).State = System.Data.Entity.EntityState.Modified;
                data.SaveChanges();
                return Json(new { success = true, isAcive = item.IsActive });
            }

            return Json(new { success = false });
        }
        // sử lí hiện tran Home
        [HttpPost]
        public ActionResult IsHome(int id)
        {
            var item = data.Products.Find(id);
            if (item != null)
            {
                item.IsHome = !item.IsHome;
                data.Entry(item).State = System.Data.Entity.EntityState.Modified;
                data.SaveChanges();
                return Json(new { success = true, IsHome = item.IsHome });
            }

            return Json(new { success = false });
        }

        // sử lí phần hiện sale
        [HttpPost]
        public ActionResult IsSale(int id)
        {
            var item = data.Products.Find(id);
            if (item != null)
            {
                item.IsSale = !item.IsSale;
                data.Entry(item).State = System.Data.Entity.EntityState.Modified;
                data.SaveChanges();
                return Json(new { success = true, IsSale = item.IsSale });
            }

            return Json(new { success = false });
        }
    }
}
    

WEBBANDIENTHOAI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;

namespace WEBBANDIENTHOAI.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        //ngoài trang index home
        public ActionResult MenuTop()
        {
            var items = data.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("_MenuTop", items);
        }
        //ngoài trang index home
        public ActionResult MenuProductCategory()
        {
            var items = data.ProductCategories.ToList();
            return PartialView("_MenuProductCategory", items);
        }

        //ngoài trang index home
        public ActionResult MenuProductRight(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = data.ProductCategories.ToList();
            return PartialView("_MenuProductRight", items);
        }


        // trong trang Product
        public ActionResult MnTraiProduct(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = data.ProductCategories.ToList();
            return PartialView("_MnTraiProduct", items);
        }
    }
}

WEBBANDIENTHOAI/Controllers/ProductsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEBBANDIENTHOAI.Models;
using WEBBANDIENTHOAI.Models.MFC;

namespace WEBBANDIENTHOAI.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext data = new ApplicationDbContext();
        // GET: Products

        // phần Product sản phẩm trang show all sản phẩm
        public ActionResult Index(int? page, string Searchtext, string sortOrder)
        {
            ViewBag.SortByName = String.IsNullOrEmpty(sortOrder) ?"ten_desc" : "";
            ViewBag.SortByPrice = (sortOrder == "dongia" ? "dongia_desc" : "dongia"); 
          
            IEnumerable<Product> items = data.Products.OrderByDescending(x => x.Id);
           
            switch(sortOrder)
            {
                case "ten_desc":
                    items = data.Products.OrderByDescending(x => x.Title);
                    break;
                case "dongia_desc":
                    items = data.Products.OrderByDescending(x => x.Price);
                    break;
                case "dongia":
                    items = data.Products.OrderBy(x => x.Price);
                    break;
                default: // mặc định sắp xếp theo tên sản phẩm
                    items = data.Products.OrderBy(x => x.Title);
                    break;

            }
          
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }

            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
           
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
            //var items = data.Products.ToList();

            //return View(items);

        }

        // chi tiết sản phẩm sản phẩm 
        public ActionResult Detail(string alias, int id)
        {
            var item = data.Products.Find(id);
            // đếm số lượt truy cập vô sản phẩm đó
            if (item != null)
            {
                data.Products.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                data.Entry(item).Property(x => x.ViewCount).IsModified = true;
                data.SaveChanges();
            }

            return View(item);
        }

        // Trang sản phẩm nhưng theo danh mục ấn vào danh mục điện thoại thì sẻ sử lí show trang điện thoại
        public ActionResult ProductCategory(string alias, int id, string Searchtext, string sortOrder, int? page)
        {

            ViewBag.SortByName = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.SortByPrice = (sortOrder == "dongia" ? "dongia_desc" : "dongia");

            IEnumerable<Product> items = data.Products.OrderByDescending(x => x.Id);

            switch (sortOrder)
            {
                case "ten_desc":
                    items = data.Products.OrderByDescending(x => x.Title);
                    break;
                case "dongia_desc":
                    items = data.Products.OrderByDescending(x => x.Price);
                    break;
                case "dongia":
                    items = data.Products.OrderBy(x => x.Price);
                    break;
                default: // mặc định sắp xếp theo tên sản phẩm
                    items = data.Products.OrderBy(x => x.Title);
                    break;

            }

            //var items = data.Products.ToList();
            if (id > 0)
            {
                items = items.Where(x => x.ProductCategoryId == id).ToList();
            }
            var cate = data.ProductCategories.Find(id);
            if (cate != null)
            {
                ViewBag.CateName = cate.Title;
            }
            var CateId = 5;
            if (page == null)
            {
                page = 1;
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, CateId);
            ViewBag.CateId = id;
            ViewBag.Page = page;
            return View(items);
        }


        // sử lí từng phần sản phẩm theo tên sản phẩm ngoài trang chủ, Điện Thoai, Máy Tính, Đồng Hồ
        public ActionResult Partial_ItemsByCateId()
        {
            var items = data.Products.Where(x => x.IsHome && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

        //
        public ActionResult ProductSales()
        {
            var items = data.Products.Where(x => x.IsSale && x.IsActive).Take(12).ToList();
            return PartialView(items);
        }

       
    }
}

WEBBANDIENTHOAI/Views/Products/ProductCategory.cshtml
@*@model PagedList.PagedList<WEBBANDIENTHOAI.Models.MFC.Product>
    @using PagedList;
    @using PagedList.Mvc;*@
@*@model IEnumerable<WEBBANDIENTHOAI.Models.MFC.Product>*@
@model PagedList.PagedList<WEBBANDIENTHOAI.Models.MFC.Product>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh Sách Sản Phẩm";

}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">



        <!-- ============================  FILTER TOP  ================================= -->
        <div class="card mb-3">
            <div class="card-body">
                <ol class="breadcrumb float-left">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Category name</a></li>
                    <li class="breadcrumb-item active">Item details</li>
                </ol>
            </div> <!-- card-body .// -->
        </div> <!-- card.// -->
        <!-- ============================ FILTER TOP END.// ================================= -->


        <div class="row">
            <aside class="col-md-2">


                <article class="filter-group">
                    <h6 class="title">
                        <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target="#collapse_2"> Danh Mục Sản Phẩm</a>
                    </h6>
                    @Html.Action("MnTraiProduct", "Menu", new { id = ViewBag.CateId })
                    <!--<div class="filter-content collapse show" id="collapse_2">-->
                    @*@foreach (var item in Model)*@
                    <!--{
                    <div class="inner">

                        <label class="custom-control custom-checkbox">
                            <input type="checkbox" checked="" class="custom-control-input">
                            <div class="custom-control-label">-->
                    @*@item.Name*@
                    <!--<b class="badge badge-pill badge-light float-right">-->@*@item.quantity*@
                    <!--</b>
                            </div>
                        </label>

                    </div>-->
                    <!-- inner.// -->
                    <!--}
                    </div>-->
                </article> <!-- filter-group .// -->
                <article class="filter-group">
                    <h6 class="title">
                        <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target="#collapse_3"> Mức Giá </a>
                    </h6>
                    <div class="filter-content collapse show" id="collapse_3">
                        @Html.ActionLink("Tên sản phẩm |", "ProductCategory", new { sortOrder = ViewBag.SortByName })
                        @Html.ActionLink("Đơn giá", "ProductCategory", new { sortOrder = ViewBag.SortByPrice })
                        <div class="inner">
                            <input type="range" class="custom-range" min="0" max="100" name="">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Min</label>
                                    <input class="form-control" placeholder="0 VNĐ" type="number">
                                </div>
                                <div class="form-group text-right col-md-6">
                                    <label>Max</label>
                                    <input class="form-control" placeholder="10,0000,000 VNĐ" type="number">
                                </div>
                            </div> <!-- form-row.// -->
                            <button class="btn btn-block btn-primary">Cập nhật</button>
                        </div> <!-- inner.// -->
                    </div>
                </article> <!-- filter-group .// -->



            </aside> <!-- col.// -->
            <main class="col-md-10">


                <header class="mb-3">
                    <div class="form-inline">
                        <strong class="mr-md-auto">32 Items found </strong>
                        <select class="mr-2 form-control">
                            <option>Latest items</option>
                            <option>Trending</option>
                            <option>Most Popular</option>
                            <option>Cheapest</option>
                        </select>
                        <div class="btn-group">
                            <a href="page-listing-grid.html" class="btn btn-light" data-toggle="tooltip" title="List view">
                                <i class="fa fa-bars"></i>
                            </a>
                            <a href="page-listing-large.html" class="btn btn-light active" data-toggle="tooltip" title="Grid view">
                                <i class="fa fa-th"></i>
                            </a>
                        </div>
                    </div>
                </header><!-- sect-heading -->

                @if (Model != null && Model.Any())
                {
                    foreach (var item in Model)
                    {
                        var strImge = "";
                        var img = item.ProductImage.FirstOrDefault(x => x.IsDefault);
                        if (img != null)
                        {
                            strImge = img.Image;
                        }
                        <article class="card card-product-list">
                            <div class="row no-gutters">
                                <aside class="col-md-3">
                                    @*<a href="@Url.Action("Detail", "Product", new { Id = item.Id })" class="img-wrap">
                                            <span class="badge badge-danger"> NEW </span>
                                            <img src="~/Content/images/@item.Avartar">
                                        </a>*@
                                    <div class="product_image">
                                        <a href="/chi-tiet/@item.Alias-p@(item.Id)"><img src="@strImge" alt="@item.Title"></a>

                                    </div>

                                </aside> <!-- col.// -->
                                <div class="col-md-6">
                                    <div class="info-main">

                                        <div class="product_info">
                                            @if (item.PriceSale > 0)
                                            {
                                                <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span style=" color: #fff; background-color: #fa3434; border-radius:10px; margin-right: 750px;">Sale!!</span></div>
                                            }
                                            else
                                            {
                                                <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span style=" color: #fff; background-color: #fa3434; border-radius: 10px; margin-right: 750px;">Hot!!</span></div>
                                            }
                                            <h6 class="product_name"><a href="/chi-tiet/@item.Alias-p@(item.Id)">@item.Title</a></h6>

                                            @if (item.PriceSale > 0)
                                            {

                                                <div class="product_price">@String.Format("{0:0,0}", @item.PriceSale) VNĐ</div>

                                            }
                                            else
                                            {
                                                <div class="product_price">@String.Format("{0:0,0}", @item.Price) VNĐ</div>
                                            }
                                        </div>
                                        @*<div class="btn btn-success"><a href="#" class="btnAddToCart" data-id="@item.Id"> Thêm Giỏ Hàng</a></div>*@
                                        <a href="#" class="btn  btn-primary">
                                            <i class="fas fa-shopping-cart"></i> <span class="btnAddToCart" data-id="@item.Id">Add to cart</span>
                                        </a>
                                        @*<a href="#" class="h5 title"> @item.Name</a>*@
                                        @*@Html.ActionLink(item.Name, "Detail", "Product", new { Id = item.Id }, null)*@

                                        <div class="rating-wrap mb-2">
                                            <ul class="rating-stars">
                                                <li style="width:100%" class="stars-active">
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </li>
                                                <li>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </li>
                                            </ul>
                                            <div class="label-rating">9/10</div>
                                        </div> <!-- rating-wrap.// -->

                                        <p class="mb-3">
                                            <span class="tag"> <i class="fa fa-check"></i> Đã xác minh</span>
                                            <span class="tag"> 5 năm </span>
                                            <span class="tag"> 80 đánh giá </span>
                                            <span class="tag"> Việt Nam </span>
                                        </p>

                                        <p>
                                            @*@item.ShortDes*@
                                        </p>

                                    </div> <!-- info-main.// -->
                                </div> <!-- col.// -->
                                <aside class="col-sm-3">
                                    <div class="info-aside">
                                        <div class="price-wrap">
                                            @*<span class="h5 price"> @String.Format("{0:0,0}", @item.Price) VNĐ</span>*@
                                            <small class="text-muted">/sản phẩm</small>
                                        </div> <!-- price-wrap.// -->
                                        <small class="text-warning">Trả tiền vận chuyển</small>

                                        <p class="text-muted mt-3">Công ty JTech</p>
                                        <p class="mt-3">
                                            <a href="#" class="btn btn-outline-primary"> <i class="fa fa-envelope"></i> Liên hệ với nhà cung cấp </a>
                                            <a href="#" class="btn btn-light"><i class="fa fa-heart"></i> Save </a>
                                        </p>

                                        <label class="custom-control mt-3 custom-checkbox">
                                            <input type="checkbox" class="custom-control-input">
                                            <div class="custom-control-label">
                                                Thêm vào để so sánh
                                            </div>
                                        </label>

                                    </div> <!-- info-aside.// -->
                                </aside> <!-- col.// -->
                            </div> <!-- row.// -->
                        </article> <!-- card-product .// -->

                    }


                }






                @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, currentFilter = ViewBag.CurrentFilter }))*@
                <nav class="mb-4" aria-label="Page navigation sample">
                    @*<ul class="pagination">
                            <li class="page-item disabled"><a class="page-link" href="#">Trang</a></li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">4</a></li>
                            <li class="page-item"><a class="page-link" href="#">5</a></li>
                            <li class="page-item"><a class="page-link" href="#">Tiếp</a></li>
                        </ul>*@
                    <div class="row">

                        <div class="col-6" style="text-align:left;">
                            @Html.PagedListPager(Model, page => Url.Action("Index",
                            new
                                 {
                                page,
                                sortOrder = ViewBag.CurrentSort
                            }))
                        </div>
                    </div>
                </nav>





            </main> <!-- col.// -->

        </div>

    </div> <!-- container .//  -->

</section>